# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "lambda-sam-playwright-v2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
s3_prefix = "lambda-sam-playwright-v2"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[stg.deploy.parameters]
stack_name = "lambda-sam-playwright-v2"
resolve_s3 = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
resolve_image_repos = true
confirm_changeset = true
