# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
parameter_overrides = [
  "Env=local",
]

[default.build.parameters]
cached = true
parallel = true
build_in_source = true

[default.validate.parameters]
lint = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[stg.deploy.parameters]
stack_name = "lambda-sam-playwright-v2-stg"
resolve_s3 = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
resolve_image_repos = true
confirm_changeset = true
parameter_overrides = [
  "Env=stg",
]

[prd.deploy.parameters]
stack_name = "lambda-sam-playwright-v2-prd"
resolve_s3 = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
resolve_image_repos = true
confirm_changeset = true
parameter_overrides = [
  "Env=prd",
]
